export const dashjs = {
  listeners: [
    'bufferLevelUpdated',
    'bufferLoaded',
    'bufferStalled',
    'bufferStateChanged',
    'canPlay',
    'canPlayThrough',
    'manifestLoaded',
    'playbackEnded',
    'playbackError',
    'playbackLoadedData',
    'playbackMetaDataLoaded',
    'playbackNotAllowed',
    'playbackPaused',
    'playbackPlaying',
    'playbackProgress',
    'playbackRateChanged',
    'playbackSeekAsked',
    'playbackSeeked',
    'playbackSeeking',
    'PlaybackSeekingEvent',
    'playbackStalled',
    'playbackStarted',
    'playbackTimeUpdated',
    'playbackWaiting',
  ],
};
